import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "../../providers/NextAuthSessionProvider";
import ToastProvider from "../../providers/ToastProvider";
import { Providers } from "@/store/Provider";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medicare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <NextAuthSessionProvider>
          <Providers>
            {/* <div className="max-w-[1440px] mx-auto">
              <Navbar />
              <div className="flex flex-row bg-[#F9F9F9]">
                <Sidebar /> */}
                {children}
              {/* </div>
            </div> */}
          </Providers>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
